INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('ARMHOLE + BOTTOM + POCKET', 0, '夹圈+脚围+口袋', '夾圈+腳圍+口袋');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BACK', 0, '后幅', '後幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BACK BODY', 0, '后幅', '後幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BACK BODY+LINING', 0, '后幅+ 里布', '後幅+ 裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BELT', 0, '腰带', '腰帶');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BLOCKING', 0, '拼幅', '拼幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BODY ', 0, '大身', '大身');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BODY LINING', 0, '大身里布', '大身裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BOTTOM', 0, '下身', '下身');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BUCKLE', 0, '扣', '扣');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COATING', 0, '涂层', '塗層');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR', 0, '领', '領');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+BOTTOM', 0, '领+脚围', '領+腳圍');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+BOTTOM+POCKET OPENING', 0, '领+脚围+袋口', '領+腳圍+袋口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+CUFF', 0, '领+袖口', '領+袖口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+CUFF+BOTTOM', 0, '领+袖口+脚围', '領+袖口+腳圍');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+CUFF+BOTTOM+POCKET OPENING', 0, '领+袖口+脚围+袋口', '領+袖口+腳圍+袋口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+CUFF+POCKET OPENING', 0, '领+袖口+袋口', '領+袖口+袋口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+PIN-TUCK+SLEEVE SLIT+CUFF', 0, '领+打褶+袖叉+袖', '領+打褶+袖叉+袖');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+PIN-TUCK+SLEEVE SLIT+CUFF+PLACKET', 0, '领+打褶+袖叉+袖+前筒', '領+打褶+袖叉+袖+前筒');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+PLACKET+RUFFLE+BACK YOKE LINING', 0, '领+前筒+毛+担干里布', '領+前筒+毛+擔幹裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('COLLAR+SLEEVES', 0, '领+袖', '領+袖');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('CONTRAST', 0, '撞布', '撞布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('CUFF', 0, '袖口', '袖口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('CUFF+BOTTOM', 0, '袖口+脚围', '袖口+腳圍');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('CUFF+BOTTOM+POCKET OPENING', 0, '袖口+脚围+袋口', '袖口+腳圍+袋口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('DETACHABLE FUR', 0, '可拆毛', '可拆毛');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('DETACHABLE LINING', 0, '可拆里布', '可拆裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('DETACHED FUR', 0, '可拆毛', '可拆毛');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FACE', 0, '正面', '正面');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FRONT', 0, '前幅', '前幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FRONT BLOCKING', 0, '前幅拼幅', '前幅拼幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FRONT BODY', 0, '前幅', '前幅');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FUR', 0, '毛', '毛');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('HOOD', 0, '帽', '帽');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('HOOD + BODY LINING', 0, '帽+大身里布', '帽+大身裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('HOOD + SLEEVE LINING', 0, '帽+袖里布', '帽+袖裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('HOOD LINING', 0, '帽里布', '帽裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('INNERSHELL', 0, '内里', '內裡');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('JACKET', 0, '夹克', '夾克');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('KNIT FABRIC', 0, '针织布', '針織布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LINING', 0, '里布', '裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LOWER BODY LINING + SLEEVE LINING', 0, '下身里布+袖子里布', '下身裡布+袖子裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LOWER BODY LINING + SLEEVE LINING + HOOD LINING', 0, '下身里布+袖子里布+帽里布', '下身裡布+袖子裡布+帽裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LOWER BODY+SLEEVE+HOOD LINING', 0, '下身+袖子+帽里布', '下身+袖子+帽裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('MESH', 0, '网眼布', '網眼布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('OUTERSHELL', 0, '外层面布', '外層面布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('PATCH FABRIC', 0, '贴布', '貼布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('POCKET OPENING', 0, '袋口', '袋口');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHELL FABRIC', 0, '面料', '面料');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHELL FABRIC (BACK)', 0, '面料（反面）', '面料（反面）');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHELL FABRIC (FACE)', 0, '面料（正面）', '面料（正面）');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHORTS', 0, '短裤', '短褲');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SLEEVE LINING', 0, '袖子里', '袖子裡');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SLEEVES', 0, '袖子', '袖子');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('TRIM', 0, '配件', '配件');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('UPPER BODY LINING ', 0, '上身里布', '上身裡布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('UPPER BODY LINING + HOOD LINING', 0, '上身里布+帽布', '上身裡布+帽布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('WOVEN FABRIC', 0, '梭织布', '梭織布');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('BASE', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('PANTCOURT', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('PEAK', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('PILE ', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('PADDING', 0, '填充物', '塡充物');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('FILLING', 0, '填充物', '塡充物');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SLEEVE PADDING', 0, '袖子填充物', '袖子塡充物');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('WRIST', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('WRIST OF SHIRT', 0, NULL, NULL);
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHELL FABRIC 1', 0, '面料 1', '面料 1');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('SHELL FABRIC 2', 0, '面料 2', '面料 2');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LINING 1', 0, '里布 1', '裡布 1');
INSERT INTO "bossini_parts" ("content", "status", "content_s_c", "content_t_c") VALUES ('LINING 2', 0, '里布 2', '裡布 2');
